<section class="register">
	<h2>Login </h2>
<?php if ($this->error): ?>
<p class="error">There were one or more issues with your submission.
		Please correct them as indicated below.</p>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare ();
$form->setAttribute ( 'action', $this->url ( NULL, array (
		'controller' => 'index',
		'action' => 'process' 
) ) );
$form->setAttribute ( 'method', 'post' );
echo $this->form ()->openTag ( $form );
?>

<dl class="zend_form">
		



		<dd><?php
		echo $this->formElement ( $form->get ( 'email' ) );
		echo $this->formElementErrors ( $form->get ( 'email' ) );
		?></dd>
		
		<dt><?php		
		echo $this->formLabel ( $form->get ( 'password' ) );
		?></dt>
		<dd><?php
		echo $this->formElement ( $form->get ( 'password' ) );
		echo $this->formElementErrors ( $form->get ( 'password' ) );
		?></dd>
		<dt></dd>
		<dd><?php
		echo $this->formElement ( $form->get ( 'submit' ) );
		echo $this->formElementErrors ( $form->get ( 'submit' ) );
		?></dd>
</dl>
